---
abstract: 'adds is_<day of week> method to Time::Piece '
author:
  - 'Jesse Shy <jshy@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.023
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.2, Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Time-Piece-DayOfWeek
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Time::Piece: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/jshy/Time-Piece-DayOfWeek/issues
  homepage: https://github.com/jshy/Time-Piece-DayOfWeek
  repository: https://github.com/jshy/Time-Piece-DayOfWeek.git
version: 0.01
x_contributors:
  - 'jshy <finn.cool@yahoo.com>'
